[package]
name = "rust_http"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
bcrypt = "0.17.1"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = "1.48.0"
uuid = { version = "1.18.1", features = ["v4"] }
